# Nomor 1
![Soal nomor 1](1.png)

## Point A
Sederhananya, operasi flip merupakan melakukan mirroring pada gambar dengan sumbu x sebagai tumpuan

In [157]:
def A(): # flip = upside down
    image = np.array([
        [176, 94, 201, 219],
        [37, 161, 16, 88],
        [71, 129, 177, 81],
        [41, 198, 107, 19]
    ])

    result = np.empty((0, 4))
    for row in image[::-1][:]:
        result = np.vstack((result, row))
        
    print(f"Image:\n {image}")
    print(f"Result:\n {result}")
A()

Image:
 [[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]]
Result:
 [[ 41. 198. 107.  19.]
 [ 71. 129. 177.  81.]
 [ 37. 161.  16.  88.]
 [176.  94. 201. 219.]]


## Point B
Sederhananya, operasi flop merupakan melakukan mirroring dengan sumbu y sebagai sebagai tumpuan

In [158]:
def B():
    image = np.array([
        [176, 94, 201, 219],
        [37, 161, 16, 88],
        [71, 129, 177, 81],
        [41, 198, 107, 19]
    ])

    result = np.empty((0, 4))
    for row in image[:]:
        result = np.vstack((result, np.flip(row)))

    print(f"Image:\n {image}")
    print(f"Result:\n {result}")
    
B()

Image:
 [[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]]
Result:
 [[219. 201.  94. 176.]
 [ 88.  16. 161.  37.]
 [ 81. 177. 129.  71.]
 [ 19. 107. 198.  41.]]


## Point C
Sederhananya, ini adalah gabungan dari operasi flip dan flop

In [159]:
def C():
    image = np.array([
        [176, 94, 201, 219],
        [37, 161, 16, 88],
        [71, 129, 177, 81],
        [41, 198, 107, 19]
    ])

    result = np.empty((0, 4))
    for row in image[::-1][:]:
        result = np.vstack((result, np.flip(row)))

    print(f"Image:\n {image}")
    print(f"Result:\n {result}")
C()

Image:
 [[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]]
Result:
 [[ 19. 107. 198.  41.]
 [ 81. 177. 129.  71.]
 [ 88.  16. 161.  37.]
 [219. 201.  94. 176.]]


## Point D
Sederhananya, operasi ini menghasilkan nilai dari suatu pixel seandainya diambil dari ujung interval sebaliknya (Misal 37 menjadi 218 karena kita mulai dari 255, maka nilai yang dihasilkan adalah 255 - 37)

In [160]:
def D():
    image = np.array([
        [176, 94, 201, 219],
        [37, 161, 16, 88],
        [71, 129, 177, 81],
        [41, 198, 107, 19]
    ])
    MAX_INTENSITY = 255
    
    result = (np.copy(image) * -1) + MAX_INTENSITY
    print(f"Image:\n {image}")
    print(f"Result:\n {result}")
    
D()

Image:
 [[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]]
Result:
 [[ 79 161  54  36]
 [218  94 239 167]
 [184 126  78 174]
 [214  57 148 236]]


## Point E

In [168]:
def E():
    image = np.array([
        [176, 94, 201, 219],
        [37, 161, 16, 88],
        [71, 129, 177, 81],
        [41, 198, 107, 19]
    ])

    result = np.empty((len(image[0]), len(image))) # Rotasi Citra MxN => Citra NxM

    for ydx in range(len(image[0])):
        ydx += 1 # Ubah ke 1-indexed 
        for xdx in range(len(image)):
            xdx += 1 # Ubah ke 1-indexed

            # cos(90deg) == 0 jadi abaikan
            yNew = -xdx
            xNew = ydx - 1
            if yNew < 0: yNew += len(image)
            xdx -= 1 # Kembalikan ke 0-indexed
    
            result[ydx - 1][xdx] = image[yNew][xNew] # Kembalikan ke 0-indexed
            
    print(f"Image:\n {image}")
    print(f"Result:\n {result}")
E()

Image:
 [[176  94 201 219]
 [ 37 161  16  88]
 [ 71 129 177  81]
 [ 41 198 107  19]]
Result:
 [[ 41.  71.  37. 176.]
 [198. 129. 161.  94.]
 [107. 177.  16. 201.]
 [ 19.  81.  88. 219.]]
