# Nomor 2
![Soal nomor 2](2.png)

In [15]:
import numpy as np

## Poin A
Operasi ini menambahkan nilai setiap pixel pada satu citra ke citra lainnya

In [16]:
def A():
    image1 = np.array([
        [19, 171, 91, 68],
        [123, 99, 74, 195],
        [85, 71, 208, 18],
        [241, 212, 189, 68]
    ])

    image2 = np.array([
        [106, 97, 190, 5],
        [81, 64, 183, 82],
        [71, 200, 251, 94],
        [181, 76, 9, 18]
    ])

    result = np.empty((4, 4))
    for ydx in range(len(image1)):
        for xdx in range(len(image1[ydx])):
            res = image1[ydx][xdx] + image2[ydx][xdx]
            if(res > 255):
                res = 255
            result[ydx][xdx] = res
    print(f"Result:\n {result}")

    
A()

Result:
 [[125. 255. 255.  73.]
 [204. 163. 255. 255.]
 [156. 255. 255. 112.]
 [255. 255. 198.  86.]]


## Poin B
Operasi ini melakukan pengurangan nilai pixel pada suatu citra dengan citra lainnya dengan hasil nilai yang negatif diubah menjadi 0

In [17]:
def B():
    image1 = np.array([
        [19, 171, 91, 68],
        [123, 99, 74, 195],
        [85, 71, 208, 18],
        [241, 212, 189, 68]
    ])

    image2 = np.array([
        [106, 97, 190, 5],
        [81, 64, 183, 82],
        [71, 200, 251, 94],
        [181, 76, 9, 18]
    ])

    result = np.empty((4, 4))
    for ydx in range(len(image1)):
        for xdx in range(len(image1[ydx])):
            res = image1[ydx][xdx] - image2[ydx][xdx]
            if(res < 0):
                res = 0
            result[ydx][xdx] = res
    print(f"Result:\n {result}")

    
B()

Result:
 [[  0.  74.   0.  63.]
 [ 42.  35.   0. 113.]
 [ 14.   0.   0.   0.]
 [ 60. 136. 180.  50.]]


## Poin C
Operasi ini sama seperti operasi difference, hanya saja yang didapatkan adalah selisih nilai pixel pada suatu citra dengan citra lainnya

In [18]:
def C():
    image1 = np.array([
        [19, 171, 91, 68],
        [123, 99, 74, 195],
        [85, 71, 208, 18],
        [241, 212, 189, 68]
    ])

    image2 = np.array([
        [106, 97, 190, 5],
        [81, 64, 183, 82],
        [71, 200, 251, 94],
        [181, 76, 9, 18]
    ])

    result = np.empty((4, 4))
    for ydx in range(len(image1)):
        for xdx in range(len(image1[ydx])):
            res = image1[ydx][xdx] - image2[ydx][xdx]
            if(res < 0):
                res *= -1
            result[ydx][xdx] = res
    print(f"Result:\n {result}")

    
C()

Result:
 [[ 87.  74.  99.  63.]
 [ 42.  35. 109. 113.]
 [ 14. 129.  43.  76.]
 [ 60. 136. 180.  50.]]
